os: osx

language: scala
scala:
  - 2.12.14
  - 2.13.6
  - 3.0.0
jdk:
  - oraclejdk9
  - openjdk9
  - openjdk10
  - openjdk11
  - openjdk12
  - openjdk13
  - openjdk14
  - openjdk15

sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
before_cache:
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean test
